spring:
  application:
    name: aprobacion-service
  datasource:
    url: jdbc:postgresql://localhost:5432/aprobaciondb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

kafka:
  bootstrap-servers: localhost:9092

server:
  port: 8082
