spring:
  application:
    name: solicitud-service
  datasource:
    url: jdbc:postgresql://localhost:5432/solicituddb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081
